int randomColors(int MIN, int MAX);
int checkColorTab(int comparedColor, char *colors, int size, int checkOnce);
int checkForbiddenColors(char *colors, int size);
void upperCase(char *colors, int size);
void Title();
char plural(int value);
void onePlayerGameInitialization(int difficulty, char *unknownColors);
void twoPlayerGameInitialization(int difficulty, char *unknownColors);
void playerScanf(int difficulty, char *colors);
void wellPlacedColorsVerification(int difficulty, int *wellPlacedColors, char *unknownColorsCopy, char *playerColors);
void misplacedColorsVerification(int difficulty, int *misplacedColors, char *unknownColorsCopy, char *playerColors);
void turnIndication(int wellPlacedColors, int misplacedColors, int turns);
void onePlayerEndMessage(int wellPlacedColors, int difficulty, char *unknownColors);
void twoPlayerEndMessage(int wellPlacedColors, int difficulty, char *unknownColors);